# Generated by Django 6.0.1 on 2026-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url_path',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
